-- [Clone Schema for Pogokhi]
-- Based on js/app.js reverse engineering + fix_rls.sql optimizations
-- TABLES: user_roles, basic_schedules, settings, departments, schedules, error_logs

-- crypt() 함수 사용을 위해 암호화 확장기능 활성화
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Table: user_roles
CREATE TABLE IF NOT EXISTS public.user_roles (
    user_id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email text,
    role text DEFAULT 'guest', -- 'admin', 'teacher', 'head_teacher', 'guest'
    status text DEFAULT 'pending', -- 'active', 'pending'
    last_login timestamp with time zone
);

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- user_roles Policies
CREATE POLICY "Public Read User Roles" ON public.user_roles FOR SELECT TO public USING (true);
-- Explicit policy for authenticated users to ensure 403 is avoided for self-lookup
CREATE POLICY "Authenticated Read Self" ON public.user_roles FOR SELECT TO authenticated 
    USING (user_id = (select auth.uid()));

-- Users can update their own last_login (handled via upsert in syncUser)
CREATE POLICY "Users Update Own Role Meta" ON public.user_roles FOR UPDATE TO authenticated 
    USING (user_id = (select auth.uid()))
    WITH CHECK (user_id = (select auth.uid()));
CREATE POLICY "Users Insert Own Role Meta" ON public.user_roles FOR INSERT TO authenticated 
    WITH CHECK (user_id = (select auth.uid()));


-- 2. Table: settings
CREATE TABLE IF NOT EXISTS public.settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year integer NOT NULL,
    school_name text,     -- Pure name (e.g. "GOE")
    full_name_kr text,    -- Display name (e.g. "GOE학교")
    name_en text,         -- English name
    level_kr text,        -- "학교"
    level_en text,        -- "School"
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- settings Policies (Optimized)
CREATE POLICY "Public Read Settings" ON public.settings FOR SELECT TO public USING (true);
CREATE POLICY "Admin Write Settings" ON public.settings FOR UPDATE TO authenticated 
    USING ((select auth.uid()) IS NOT NULL) WITH CHECK ((select auth.uid()) IS NOT NULL);
CREATE POLICY "Admin Insert Settings" ON public.settings FOR INSERT TO authenticated 
    WITH CHECK ((select auth.uid()) IS NOT NULL);


-- 3. Table: basic_schedules (Academic Calendar)
CREATE TABLE IF NOT EXISTS public.basic_schedules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year integer NOT NULL,
    type text,            -- 'term', 'vacation', 'holiday', 'exam', 'event'
    code text,            -- 'TERM1_START', etc.
    name text,            -- "여름방학"
    start_date date,
    end_date date,
    is_holiday boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.basic_schedules ENABLE ROW LEVEL SECURITY;

-- basic_schedules Policies (Optimized)
CREATE POLICY "Public Read Basic Schedules" ON public.basic_schedules FOR SELECT TO public USING (true);
CREATE POLICY "Authenticated Insert Basic Schedules" ON public.basic_schedules FOR INSERT TO authenticated 
    WITH CHECK ((select auth.uid()) IS NOT NULL);
CREATE POLICY "Authenticated Update Basic Schedules" ON public.basic_schedules FOR UPDATE TO authenticated 
    USING ((select auth.uid()) IS NOT NULL) WITH CHECK ((select auth.uid()) IS NOT NULL);
CREATE POLICY "Authenticated Delete Basic Schedules" ON public.basic_schedules FOR DELETE TO authenticated 
    USING ((select auth.uid()) IS NOT NULL);


-- 4. Table: departments
CREATE TABLE IF NOT EXISTS public.departments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year integer NOT NULL,
    dept_name text NOT NULL,
    dept_short text,
    dept_id_en text,       -- ID for department role matching (e.g. 'science')

    dept_color text DEFAULT '#3788d8',
    sort_order integer DEFAULT 0,
    is_active boolean DEFAULT true,
    is_printable boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);

-- [Migration] 기존에 departments 테이블이 이미 있는 경우 아래 명령어로 컬럼을 추가하세요:
-- ALTER TABLE public.departments ADD COLUMN IF NOT EXISTS dept_id_en text;

ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;

-- departments Policies (Optimized)
CREATE POLICY "Public Read Departments" ON public.departments FOR SELECT TO public USING (true);
CREATE POLICY "Admin Write Departments" ON public.departments FOR INSERT TO authenticated 
    WITH CHECK ((select auth.uid()) IS NOT NULL);
CREATE POLICY "Admin Update Departments" ON public.departments FOR UPDATE TO authenticated 
    USING ((select auth.uid()) IS NOT NULL) WITH CHECK ((select auth.uid()) IS NOT NULL);
CREATE POLICY "Admin Delete Departments" ON public.departments FOR DELETE TO authenticated 
    USING ((select auth.uid()) IS NOT NULL);


-- 5. Table: schedules (Main Calendar Events)
CREATE TABLE IF NOT EXISTS public.schedules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    dept_id bigint REFERENCES public.departments(id) ON DELETE SET NULL,
    dept_name text,        -- Backup name in case of dept deletion
    description text,
    visibility text DEFAULT 'public', -- 'public', 'internal', 'dept'
    author_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, -- Allow user deletion while keeping schedules
    is_printable boolean DEFAULT true,
    weekend text,          -- 'on' or null
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.schedules ENABLE ROW LEVEL SECURITY;

-- schedules Policies (Optimized)
CREATE POLICY "Public Read Schedules" ON public.schedules FOR SELECT TO public USING (true);
CREATE POLICY "Authenticated Insert Schedules" ON public.schedules FOR INSERT TO authenticated 
    WITH CHECK ((select auth.uid()) IS NOT NULL);
CREATE POLICY "Owner Update Schedules" ON public.schedules FOR UPDATE TO authenticated 
    USING (author_id = (select auth.uid())) WITH CHECK (author_id = (select auth.uid()));
CREATE POLICY "Owner Delete Schedules" ON public.schedules FOR DELETE TO authenticated 
    USING (author_id = (select auth.uid()));


-- 6. Table: error_logs
CREATE TABLE IF NOT EXISTS public.error_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_message text,
    stack_trace text,      -- Storing JSON as text
    user_id uuid,          -- Nullable for guest errors
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.error_logs ENABLE ROW LEVEL SECURITY;

-- error_logs Policies
-- NOTICE: This 'TO public' policy triggers a Supabase warning but is intentional for capturing guest errors.
CREATE POLICY "Public Insert Logs" ON public.error_logs FOR INSERT TO public WITH CHECK (true);
-- Read policy for Admins only
CREATE POLICY "Admins Read Logs" ON public.error_logs FOR SELECT TO authenticated 
    USING ((select role from public.user_roles where user_id = (select auth.uid())) = 'admin');


-- [Indexes]
CREATE INDEX IF NOT EXISTS idx_basic_schedules_year ON public.basic_schedules(academic_year);
CREATE INDEX IF NOT EXISTS idx_departments_year ON public.departments(academic_year);
CREATE INDEX IF NOT EXISTS idx_schedules_date ON public.schedules(start_date);


-- [Fix Permissions for PogokLink]
-- Grant usage and select permissions to public/anon roles to fix 401/403 errors.

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT, UPDATE ON public.user_roles TO anon, authenticated;


GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
-- 7. [Auth Logic] User Roles Auto-Registration & Migration
-- This function handles automatic insertion into public.user_roles when a new auth user is created.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.user_roles (user_id, email, role, status, last_login)
  VALUES (new.id, new.email, 'teacher', 'pending', now())
  ON CONFLICT (user_id) DO NOTHING;
  RETURN new;
END;
$$;

-- Trigger: on_auth_user_created
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_new_user();

-- Migration: Sync existing auth.users to public.user_roles if missing
INSERT INTO public.user_roles (user_id, email, role, status)
SELECT id, email, 'teacher', 'pending'
FROM auth.users
WHERE id NOT IN (SELECT user_id FROM public.user_roles)
ON CONFLICT (user_id) DO NOTHING;

